### ISSUE TITLE
Command(s) to pull docker instance and run using local config file

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/amodstore#2]
Modify the root `readme.md` to include commands to pull the docker file and run the instance using the local config file.

Add instructions to the `readme.md` on how to open the container, and a screenshot of what you see when you browse to the container.

Details here: https://docs.pygeoapi.io/en/latest/running-with-docker.html#overriding-the-default-configuration

**Comment by Vierod** [comment]
Probably the best approach here is to use the docker compose option with a docker compose YAML
```
version: "3"
services:
  pygeoapi:
    image: geopython/pygeoapi:latest
    volumes:
      - ./my.config.yml:/pygeoapi/local.config.yml
    ports:
      - "5000:80"
    environment:
     - SCRIPT_NAME=/pygeoapi
```
